import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="bg-[rgb(39,37,37)] text-white h-screen  overflow-y-scroll z-0">
      <Head>
        <title>David-Mwas-Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
        {/* header */}

        <Header/>

        {/* hero */}
        <div id="hero" className="snap-center" >
        <Hero/>
        </div>

        {/* about */}
        <div id="about" className="spap-center">
          <About/>
        </div>

        {/* Expirince */}

        {/* skill */}

        {/* projects */}
        
        {/* contacts */}
    </div>
  );
};

